USE ROLE ACCOUNTADMIN;
USE DATABASE TASTY_BYTES_DBT_DB;
USE SCHEMA DEV;

DROP TABLE CUSTOMER_LOYALTY_METRICS;
DROP TABLE ORDERS;
DROP TABLE SALES_METRICS_BY_LOCATION;

DROP VIEW RAW_CUSTOMER_CUSTOMER_LOYALTY;
DROP VIEW RAW_POS_COUNTRY;
DROP VIEW RAW_POS_FRANCHISE;
DROP VIEW RAW_POS_LOCATION;
DROP VIEW RAW_POS_MENU;
DROP VIEW RAW_POS_ORDER_DETAIL;
DROP VIEW RAW_POS_ORDER_HEADER;
DROP VIEW RAW_POS_TRUCK;